version: "3"

services:
  app:
    build: ./recording-api
    ports:
      - "8080:8080"
  
  db-mongo:
    container_name: mongodb
    image: mongo
    command: "mongod --replSet rs0"
    ports:
      - "27027:27017"
    healthcheck:
      test: mongosh --eval "rs.initiate()"
      start_period: 5s
