version: "3"

volumes:
  mongo_data: {}


services:
  app:
    build: ./recording-api
    ports:
      - "8080:6969"
  
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27027:27017"
    healthcheck:
      start_period: 5s
    volumes:
      - mongo_data:/data/db 